#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World!' |sudo tee  /var/www/html/index.html
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
sudo nginx -t
