#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# redirects to another page
# Have a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
