#!/usr/bin/env bash

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 346914-web-01 100.26.210.229:80 check
   server 346914-web-02 54.210.107.66:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
