#!/usr/bin/env bash

CONFGF="\\\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 2135-web-01 35.237.202.79 check\n\tserver 2135-web-02 34.204.185.51 check\n"

sudo apt-get update
sudo apt-get -y install nginx
sudo apt-get install -y haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo sed -i "\$a $CONFGF" /etc/haproxy/haproxy.cfg

sudo service haproxy start
