#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes

hour=0
minute=1

while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -lt 60 ]
    do
        echo $minute
	let minute+=1
    done
    let hour+=1
done
